//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Contract.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Contract;

public class Candidate implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public String candidateId;

    public String name;

    public Candidate()
    {
        this.candidateId = "";
        this.name = "";
    }

    public Candidate(String candidateId, String name)
    {
        this.candidateId = candidateId;
        this.name = name;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Candidate r = null;
        if(rhs instanceof Candidate)
        {
            r = (Candidate)rhs;
        }

        if(r != null)
        {
            if(this.candidateId != r.candidateId)
            {
                if(this.candidateId == null || r.candidateId == null || !this.candidateId.equals(r.candidateId))
                {
                    return false;
                }
            }
            if(this.name != r.name)
            {
                if(this.name == null || r.name == null || !this.name.equals(r.name))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Contract::Candidate");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, candidateId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, name);
        return h_;
    }

    public Candidate clone()
    {
        Candidate c = null;
        try
        {
            c = (Candidate)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.candidateId);
        ostr.writeString(this.name);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.candidateId = istr.readString();
        this.name = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Candidate v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Candidate ice_read(com.zeroc.Ice.InputStream istr)
    {
        Candidate v = new Candidate();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Candidate> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Candidate v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Candidate> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Candidate.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Candidate _nullMarshalValue = new Candidate();

    /** @hidden */
    public static final long serialVersionUID = -1267127688559004461L;
}
