//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Contract.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Contract;

public interface ConsultServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default String getVotingLocation(String voterId)
    {
        return getVotingLocation(voterId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getVotingLocation(String voterId, java.util.Map<String, String> context)
    {
        return _iceI_getVotingLocationAsync(voterId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getVotingLocationAsync(String voterId)
    {
        return _iceI_getVotingLocationAsync(voterId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getVotingLocationAsync(String voterId, java.util.Map<String, String> context)
    {
        return _iceI_getVotingLocationAsync(voterId, context, false);
    }

    /**
     * @hidden
     * @param iceP_voterId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getVotingLocationAsync(String iceP_voterId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getVotingLocation", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_voterId);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default void setCandidates(Candidate[] candidates)
    {
        setCandidates(candidates, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void setCandidates(Candidate[] candidates, java.util.Map<String, String> context)
    {
        _iceI_setCandidatesAsync(candidates, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> setCandidatesAsync(Candidate[] candidates)
    {
        return _iceI_setCandidatesAsync(candidates, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> setCandidatesAsync(Candidate[] candidates, java.util.Map<String, String> context)
    {
        return _iceI_setCandidatesAsync(candidates, context, false);
    }

    /**
     * @hidden
     * @param iceP_candidates -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_setCandidatesAsync(Candidate[] iceP_candidates, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setCandidates", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     CandidateSeqHelper.write(ostr, iceP_candidates);
                 }, null);
        return f;
    }

    default Candidate[] getCandidates()
    {
        return getCandidates(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Candidate[] getCandidates(java.util.Map<String, String> context)
    {
        return _iceI_getCandidatesAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Candidate[]> getCandidatesAsync()
    {
        return _iceI_getCandidatesAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Candidate[]> getCandidatesAsync(java.util.Map<String, String> context)
    {
        return _iceI_getCandidatesAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Candidate[]> _iceI_getCandidatesAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Candidate[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getCandidates", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     Candidate[] ret;
                     ret = CandidateSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default String getResults()
    {
        return getResults(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getResults(java.util.Map<String, String> context)
    {
        return _iceI_getResultsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getResultsAsync()
    {
        return _iceI_getResultsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getResultsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getResultsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getResultsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getResults", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default String getResumeCSV()
    {
        return getResumeCSV(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getResumeCSV(java.util.Map<String, String> context)
    {
        return _iceI_getResumeCSVAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getResumeCSVAsync()
    {
        return _iceI_getResumeCSVAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getResumeCSVAsync(java.util.Map<String, String> context)
    {
        return _iceI_getResumeCSVAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getResumeCSVAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getResumeCSV", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default String getPartialCSV()
    {
        return getPartialCSV(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getPartialCSV(java.util.Map<String, String> context)
    {
        return _iceI_getPartialCSVAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getPartialCSVAsync()
    {
        return _iceI_getPartialCSVAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getPartialCSVAsync(java.util.Map<String, String> context)
    {
        return _iceI_getPartialCSVAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getPartialCSVAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getPartialCSV", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ConsultServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ConsultServicePrx.class, _ConsultServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ConsultServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ConsultServicePrx.class, _ConsultServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ConsultServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ConsultServicePrx.class, _ConsultServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ConsultServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ConsultServicePrx.class, _ConsultServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ConsultServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ConsultServicePrx.class, _ConsultServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ConsultServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ConsultServicePrx.class, _ConsultServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ConsultServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ConsultServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ConsultServicePrx ice_adapterId(String newAdapterId)
    {
        return (ConsultServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ConsultServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ConsultServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ConsultServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ConsultServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ConsultServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (ConsultServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ConsultServicePrx ice_connectionCached(boolean newCache)
    {
        return (ConsultServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ConsultServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ConsultServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ConsultServicePrx ice_secure(boolean b)
    {
        return (ConsultServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ConsultServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ConsultServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ConsultServicePrx ice_preferSecure(boolean b)
    {
        return (ConsultServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ConsultServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ConsultServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ConsultServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ConsultServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ConsultServicePrx ice_collocationOptimized(boolean b)
    {
        return (ConsultServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ConsultServicePrx ice_twoway()
    {
        return (ConsultServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ConsultServicePrx ice_oneway()
    {
        return (ConsultServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ConsultServicePrx ice_batchOneway()
    {
        return (ConsultServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ConsultServicePrx ice_datagram()
    {
        return (ConsultServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ConsultServicePrx ice_batchDatagram()
    {
        return (ConsultServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ConsultServicePrx ice_compress(boolean co)
    {
        return (ConsultServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ConsultServicePrx ice_timeout(int t)
    {
        return (ConsultServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ConsultServicePrx ice_connectionId(String connectionId)
    {
        return (ConsultServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ConsultServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ConsultServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Contract::ConsultService";
    }
}
