//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Contract.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Contract;

public class Vote implements java.lang.Cloneable,
                             java.io.Serializable
{
    public String voterId;

    public String candidateId;

    public Vote()
    {
        this.voterId = "";
        this.candidateId = "";
    }

    public Vote(String voterId, String candidateId)
    {
        this.voterId = voterId;
        this.candidateId = candidateId;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Vote r = null;
        if(rhs instanceof Vote)
        {
            r = (Vote)rhs;
        }

        if(r != null)
        {
            if(this.voterId != r.voterId)
            {
                if(this.voterId == null || r.voterId == null || !this.voterId.equals(r.voterId))
                {
                    return false;
                }
            }
            if(this.candidateId != r.candidateId)
            {
                if(this.candidateId == null || r.candidateId == null || !this.candidateId.equals(r.candidateId))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Contract::Vote");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, voterId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, candidateId);
        return h_;
    }

    public Vote clone()
    {
        Vote c = null;
        try
        {
            c = (Vote)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.voterId);
        ostr.writeString(this.candidateId);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.voterId = istr.readString();
        this.candidateId = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Vote v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Vote ice_read(com.zeroc.Ice.InputStream istr)
    {
        Vote v = new Vote();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Vote> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Vote v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Vote> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Vote.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Vote _nullMarshalValue = new Vote();

    /** @hidden */
    public static final long serialVersionUID = -5506404494475480962L;
}
